### ISSUE TITLE
Arrow roadmap

### ISSUE THREAD

**Issue by blaxill** [project-oak/oak-hardware#145]
Roadmap 

- [ ] - ~~Merge multiple definitions of `Kind` back into one, and re-enable extern/uninterpreted type for arrows.~~ My current thinking is it makes sense to have a separate Arrow.Kind from the netlist kind, as I'd like to be able to represent much richer types at the arrow level.
- [x] - Require `object` be `Kind` in Arrow.Cava class. Currently this isn't a requirement and I hesitated on making this change to allow more generality but currently there is no use for this generality and it hinders work on proofs which would benefit from some sane props about object such as it has inhabitants or that it is inductively created.

Optional

- [x] - Remove lifting arbitrary morphism to kappa calculus. This would allow easy evaluation of kappa fragments, in turn allowing easy proposition on said fragments. It should be then possible to prove that certain props on kappa imply corresponding props on the circuit structure they create.
- [x] - Switch Arrow.Vector indexing to `nat` from `N`. Native Coq Vector expects nat. Motivation for keeping `N` is that extraction should be size `log2 n` whereas `nat` extraction will be linear.
